site: DesCurioso™
url: https://descurioso.com
title: DesCurioso™
description: Network S.A.
tagline: Blog dedicado à assuntos diversos
lang: pt_BR

google_analytics: UA-120280297-2

permalink: pretty
baseurl: ""

highlighter: rouge
markdown: kramdown
kramdown:
  html_to_native: true
  auto_ids: false

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name #/:categories/:name
  posts:
    output: true
    permalink: /:slug #/:year/:month/:day/:slug
  filmes:
    output: true
    permalink: /:collection/:title
  series:
    output: true
    permalink: /:collection/:title
  musicas:
    output: true
    permalink: /:collection/:title
  jogos:
    output: true
    permalink: /:collection/:title
  programas:
    output: true
    permalink: /:collection/:title
  blog:
    output: true
    permalink: /:collection/:title
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/default-card.webp
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      image: /assets/images/default-card.webp
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /assets/images/default-card.webp

paginate: 10
paginate_path: /page:num/